Repository kwizapp/ionic-app, pull requests merged in 2020-04, with the labels that each got.

#78 Update readme
  README.md
Labels: documentation

#92 Fix loading screen style
  src/components/Loading.tsx
Labels: bug

#102 37 bonus question
  package-lock.json
  package.json
  src/components/card/MovieCard.tsx
  src/components/layouts/StatsLayout.tsx
  src/pages/BonusQuestion.tsx
  src/pages/Question.tsx
  src/pages/Success.tsx
Labels: feature

#115 90 game over animation
  src/pages/GameOver.tsx
Labels: enhancement

#93 Style trivia screen
  src/components/TriviaOverlay.tsx
  src/pages/Trivia.tsx
Labels: feature
