Repository kwizapp/ionic-app, pull requests merged in 2020-05, with the labels that each got.

#136 Fix: Deployment Conditionals
  .github/workflows/main.yml
Labels: bug, devops

#151 :pencil: fix README
  README.md
Labels: documentation

#167 #149 Fix tailwind inconsistencies
  .dockerignore
  package-lock.json
  package.json
  postcss.config.js
  tailwind.config.js
Labels: bug

#171 Separate production and staging environments
  .github/workflows/main.yml
  .npmrc
Labels: devops

#178 Add release-drafter action
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: devops

#180 ⬆️ bump @kwizapp dependencies to v1.0.0
  package-lock.json
  package.json
Labels: dependencies

#181 Fix: Production Build
  .github/workflows/main.yml
Labels: bug, devops

#187 📝 add repo structure to README
  README.md
Labels: documentation

#188 Release v1.0.2
  README.md
Labels: coordination
